# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# Verify at https://fabricmc.net/develop/
minecraft_base_version=26.3
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=com.crimulus
archives_base_name=knock-on-doors

# Dependencies
fabric_version=0.160.5+26.3